name: qr-generator
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - containers
  - transformers
  - split

library:
  source-dirs: src
  exposed-modules:
    - Matrix.Model
    - Matrix.Placement
    - Matrix.Patterns
    - Encoding.Metadata
    - Encoding.Data
    - Encoding.Filler
    - Encoding.Model
    - Encoding.Encoding
    - Shared.Model
    - Shared.Error
    - Utils.BitUtils
    - ErrorCorrection.Polynomial
    - ErrorCorrection.Codewords

executables:
  qr-generator-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
      - qr-generator

tests:
  qr-generator-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
      - qr-generator     
      - hspec            
      - tasty            
      - tasty-golden     
      - bytestring
      - text
      - directory
      - filepath
    build-tools:
      - tasty-discover:tasty-discover

ghc-options:
  - -Wall
  - -Wunused-imports
  - -Wunused-matches
  - -Wunused-binds