name: qr-generator
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - containers
  - tasty-golden
  - transformers

library:
  source-dirs: src
  exposed-modules:
    - Matrix.Model
    - Matrix.Placement
    - Matrix.Patterns
    - Encoding.Metadata
    - Encoding.Data
    - Encoding.Filler
    - Shared.Model
    - Shared.Error
    - Utils.BitUtils
    - Encoding.Encoding

executables:
  qr-generator-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
      - qr-generator

tests:
  qr-generator-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
      - qr-generator     
      - hspec            
      - tasty            
      - tasty-golden     
      - bytestring
    build-tools:
      - tasty-discover:tasty-discover