name: qr-generator
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - containers

library:
  source-dirs: src
  exposed-modules:
    - Matrix.Matrix

executables:
  qr-generator-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
      - qr-generator